version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8010:8010
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql          
    networks:
      - fullstack


  fullstack-mysql:
    image: mysql/mysql-server:5.7
    container_name: full_db_mysql
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
#     - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
#     - dbdata:/var/lib/mysql
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge